xml/art-quickstart.xml, xml/product-entities.ent
Introduce `&productnameshort;` entity as discussed in SLE Writers Call on 2022-11-21.
Tahlia, I wasn't quite sure about the abbreviation. Better check that.
If you are okay with the change, I will take care of cherry-picking it into the different branches.
* DOCTEAM-828
- SLL
=> Introduce &productnameshort; entity

doc-kit.conf, xml/art-quickstart.xml, xml/common_intro_available_doc.xml, xml/common_intro_support.xml, xml/generic-entities.ent
Ran doc-kit to pull in latest updates. Changes to the common files don't impact this article, but I did need to add back some `citetitle` tags since they've been removed from the book title entities.
=> doc-kit updates Sept '23 (SLL7)

doc-kit.conf, xml/art-quickstart.xml, xml/common_intro_available_doc.xml, xml/common_intro_support.xml, xml/generic-entities.ent
Ran doc-kit to pull in latest updates. Changes to the common files don't impact this article, but I did need to add back some `citetitle` tags since they've been removed from the book title entities.
=> doc-kit updates Sept '23 (SLL8)

xml/art-quickstart.xml
Unfortunately, including this information just isn't sustainable because it constantly grows. I would really like to be able to check this via SCC, but AFAIK this isn't currently possible.
=> Remove repo size info

xml/register-with-rmt.xml
dnf is not available in SLL7, use yum instead for repository management.
=> Fix: use yum for repo management instead of dnf

xml/register-with-rmt.xml
Registration script with SLL 7 updates is available as of `rmt-server` 2.15. 
Also added a requirement to check if `yum-utils` is installed.
* GitHub Issue #20 
* Jira Issue #DOCTEAM-1403
=> SLL 7 script and requirements update

DC-lite-quickstart, xml/art-lite-quickstart.xml, xml/configure-rmt-server.xml, xml/html/rh-art-lite-quickstart.html, xml/html/rh-art-quickstart.html, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/product-entities.ent, xml/register-with-rmt.xml
Added new guide for SLL Lite. 
PDF: [art-lite-quickstart_en.pdf](https://github.com/user-attachments/files/15879828/art-lite-quickstart_en.pdf)
Open issue:
- From July 1 the SLL 7 repos will be restuctured, so the main repo won't be so enormous. But the size will still be constantly changing, so how do I stay on top of that? I would love it if we can add a function to SCC to view a repo's size.
---
Add an additional entry for the Docserv config in https://gitlab.suse.de/susedoc/docserv-config/-/merge_requests/914
=> Add new SLL Lite guide

xml/art-quickstart.xml, xml/configure-rmt-server.xml, xml/html/rh-art-quickstart.html, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/register-with-rmt.xml
After writing the VM procedure for SLL Lite, I'm now rolling it out to the other Liberty guides. 
I'm *not* including it for the SMT guide, because SLL7 is moving to LTSS soon, and SMT will no longer be supported.
* GitHub Issue #...
* Jira Issue #...
=> Add VM procedure for RMT (SLL7)

DC-quickstart-smt, xml/app-temp-script.xml, xml/art-lite-quickstart.xml, xml/art-quickstart-smt.xml, xml/art-quickstart.xml, xml/html/rh-art-lite-quickstart.html, xml/html/rh-art-quickstart.html, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/product-entities.ent, xml/register-with-rmt.xml
The SLL7 guides needed some updates for LTSS. 
* I've reduced the SMT guide down to a stub stating it is not supported, and linking to a procedure to migrate to RMT.
* I've updated the Lite guide with the new repos, but I haven't added all the Important boxes as it was already an LTSS product. 
* The new RMT script isn't available yet, so I've added it directly to the guide. It's quite long this time so I added it to an appendix that we can reuse whenever this is needed.
* Re-registration might not be working as expected so I've temporarily commented out those parts of the warnings. But they are there in the diff, and will be quick to add when it's ready.
PDFs:
Main RMT guide: 
[art-quickstart_en.pdf](https://github.com/user-attachments/files/16050387/art-quickstart_en.pdf)
Lite guide: …
=> Updates for SLL7 LTSS

xml/app-temp-script.xml, xml/art-quickstart.xml, xml/mirror-repositories-with-rmt.xml, xml/register-with-rmt.xml
Lőrinc has updated the registration script to make it work better for SLL 7 -> SLL LTSS 7 registrations. I've therefore updated the script in the appendix, and uncommented the additional  content in the `Important` admonitions now that it applies.
PDF: 
[art-quickstart_en.pdf](https://github.com/user-attachments/files/16092087/art-quickstart_en.pdf)
* Jira Issue #SLL-368
=> Update LTSS 7 registration script

xml/app-temp-script.xml, xml/art-lite-quickstart.xml, xml/art-quickstart.xml, xml/html/rh-art-lite-quickstart.html, xml/html/rh-art-quickstart.html, xml/register-with-rmt.xml
`yum-utils` can't be installed from the old CentOS 7 repos anymore, but can be from the CentOS vault. The registration script now handles this. 
* Jira Issue #SLL-369
=> New script to fix yum-utils issue

xml/art-lite-quickstart.xml, xml/art-quickstart.xml, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/register-with-rmt.xml
I'm 98% sure that last time I tested registration, LTSS-Updates and BASE-Updates were both enabled by default. 
Now only LTSS-Updates is enabled by default.
Inspired by investigating Issue #31, but technically not a fix for that.
=> More info about default and optional repos

DC-suma-quickstart, xml/art-quickstart.xml, xml/art-suma-quickstart.xml, xml/configure-rmt-server.xml, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/register-with-rmt.xml
SLL9 version of #36. This version required some changes to the table, as there is no CentOS Linux 9 so CentOS support is irrelevant. However, I didn't remove mention of it completely from the list of supported distributions, as the subscription itself still supports it, there just isn't a version 9 _to_ support. 
**PDFs:**
SUMA guide:
[art-suma-quickstart_en.pdf](https://github.com/user-attachments/files/17581489/art-suma-quickstart_en.pdf)
RMT guide new intro:
[art-quickstart_en.pdf](https://github.com/user-attachments/files/17581487/art-quickstart_en.pdf)
* Jira Issue #DOCTEAM-1621
When opening a PR, do *not* set the …
=> Add SUMA guide and clarify subscriptions (SLL9)

DC-suma-quickstart, xml/art-quickstart.xml, xml/art-suma-quickstart.xml, xml/configure-rmt-server.xml, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/register-with-rmt.xml
I've started with SLL8 because it's the cleanest to read (no big LTSS notes like SLL7, and still has CentOS unlike SLL9). 
I'll adapt it for the other versions once the overall thing is approved. 
The SUMA guide is basically a stub, but at this stage it doesn't make sense to duplicate whole SUMA guides in one little article so links will do just fine. The option is still there to possibly expand it in the future. 
The new intro required a table. I tried to keep it as minimal as possible, and it's still much easier to read than the two itemlists I'd have needed otherwise.
**PDFs:**
SUMA guide: 
[art-suma-quickstart_en.pdf](https://github.com/user-attachments/files/17552772/art-suma-quickstart_en.pdf)
RMT guide new intro: 
[art-quickstart_en.pdf](https://github.com/user-attachments/files/175 …
=> Add SUMA guide and clarify subscriptions (SLL8)

DC-suma-quickstart, xml/art-quickstart.xml, xml/art-suma-quickstart.xml, xml/configure-rmt-server.xml, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/register-with-rmt.xml
SLL7 version of #36. This version required some small changes related to LTSS: removing references to the HA extension and adding the Important admonitions.
**PDFs:**
SUMA guide:
[art-suma-quickstart_en.pdf](https://github.com/user-attachments/files/17582670/art-suma-quickstart_en.pdf)
RMT guide new intro:
[art-quickstart_en.pdf](https://github.com/user-attachments/files/17582664/art-quickstart_en.pdf)
* GitHub Issue #...
* Jira Issue #DOCTEAM-1621
=> Add SUMA guide and clarify subscriptions (SLL7)

xml/art-quickstart.xml, xml/art-suma-quickstart.xml, xml/install-rmt-vm.xml
SLL8 version of #39. A SLES entitlement for RMT use is now available with all subscription levels.
* Jira Issue #DOCTEAM-1656
=> RMT is now available with all subs (SLL8)

xml/art-quickstart.xml, xml/art-suma-quickstart.xml, xml/install-rmt-vm.xml
SLL7 version of #39. A SLES entitlement for RMT use is now available with all subscription levels.
* GitHub Issue #...
* Jira Issue #DOCTEAM-1656
=>  RMT is now available with all subs (SLL7)

xml/art-quickstart.xml, xml/art-suma-quickstart.xml, xml/install-rmt-vm.xml, xml/mirror-repositories-with-rmt.xml, xml/product-entities.ent, xml/register-with-rmt.xml
As seen in https://www.suse.com/products/multi-linux-support/, Liberty's name has changed. I've updated where I was able, but some things like repo names and IDs have not changed yet (and might not until the next version). 
I'll update SUMA to Multi-Linux Manager separately. 
Backporting will not be completely simple; it will require additional changes for each version. 
* Jira Issue #DOCTEAM-1657
=> Change name to Multi-Linux Support

xml/app-access-src-debug.xml, xml/art-compliance-scans.xml, xml/art-quickstart.xml, xml/art-suma-quickstart.xml, xml/mirror-repositories-with-rmt.xml, xml/register-with-rmt.xml
The HA repos are now available with 7 LTSS. However, instead of a separate extension, they're just part of the regular LTSS subscription. This required some significant changes to the RMT guide, but only minor changes in other guides.
PDF for the RMT guide, which had the most changes: 
[art-quickstart_en.pdf](https://github.com/user-attachments/files/19310910/art-quickstart_en.pdf)
PDFs for the other guides, which only needed minimal changes:
[art-suma-quickstart_en.pdf](https://github.com/user-attachments/files/19310065/art-suma-quickstart_en.pdf)
[art-compliance-scans_en.pdf](https://github.com/user-attachments/files/19310066/art-compliance-scans_en.pdf)
* Jira Issue #SLL-536
The doc team member merging …
=> Add HA back to 7 LTSS

.gitignore, doc-kit.conf, xml/generic-entities.ent
@tahliar : This PR contains a doc-kit run to fetch the latest updates for the files that are managed by doc-kit. 
The `generic-entities.ent` provides you with the recent productname updates, the major ones being:
- 'SUSE Manager' to 'SUSE Multi-Linux Manager' (note: I did _not_ change the values of existing SuMa entities (as for our versioned docs we still need the old product name in our maintenance branches), but added new entities for SMLM. The first 'SuMa' version with the new name will be published at the same time like SLE 15 SP7, so in case you want to replace any `susemgr/suma/*` entities used within your XML files with the new `smlm*` entities for the next release of SUSE Multi-Linux Support, you can go ahead now in `main`. 
- SUSE Liberty Linux to SUSE Multi-Linux Support (in …
=> doc-kit run (fetch updates)
